spring:
  application:
    name: legendary-ai
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        model: deepseek-v4-flash
        # model: deepseek-v4-pro
  mail:
    host: smtp.qq.com
    port: 465
    username: mjd507@qq.com
    password: ${mail_authorization_code}
    protocol: smtp
    ssl:
      enabled: true
    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000

inbound-mail:
  host: imap.qq.com
  port: 993
  username: mjd507@qq.com
  password: ${mail_authorization_code}
  protocol: imaps
